### ISSUE TITLE
Add a new defaults file for El Capitan

### ISSUE THREAD

**Issue by PolCPP** [jide/clamp#11]
Yosemite's default file works fine (at least for me) with El Capitan, but since there's no defaults file for it, it tries to load the one from Mavericks and ends failing to launch. So yeah just adding a copy of clamp.defaults.14.json as clamp.defaults.15.json does the job.

Alternatively making ConfigOptionsParser check for the most recent defaults.xx.json file could be a cleaner solution. I'll send a PR tomorrow/tuesday if you're ok with it.

And going a bit offtopic: Thanks for such a nice tool ;)

**Comment by jide** [comment]
Hello @PolCPP,

Indeed, that's not very clever ! I'm of course okay for a PR.

On a related topic, I was thinking about using homebrew for apache and php too, so it would be easy to choose a specific version of them easily instead of relying on the os ones.

But I don't have a lot of time to maintain this tool and few people seem to use it so I did not think it was worth it.

I'm glad some people like you find it useful though :)

**Comment by jide** [comment]
https://github.com/perasmus/clamp/commit/ac202f05f7a35c90d61e1308dd2a5f19da824873

**Comment by PolCPP** [comment]
I think it's a visibility issue, most people tend to use mamp/xampp because thats what they've been using all the time. I actually found about it while looking for mamp alternatives since i wasn't very happy with the latest version

**Comment by jide** [comment]
Finally did it !
