### ISSUE TITLE
Lockfile error when running clamp

### ISSUE THREAD

**Issue by eivindml** [jide/clamp#18]
Fresh install of clamp gives this: 

```
AH00526: Syntax error on line 6 of -c/-C directives:
Invalid command 'lockfile', perhaps misspelled or defined by a module not included in the server configuration
```

**Comment by rqelibari** [comment]
This error is caused by Apache.
> _LockFile_ is one of the directives of Apache ≤ 2.2. This was replaced by Mutex in Apache 2.4, which is the version of Apache installed with OS X 10.11, El Capitan.

Taken from this [Stackexchange](http://apple.stackexchange.com/questions/211015/el-capitan-apache-error-message-ah00526) answer.

Besides that Apache now also needs to load mod_unixd.so to use the _user_ command. I am currently working on a patch for this in my [fork](https://github.com/rqelibari/clamp).

If you want a quick and dirty fix follow these steps:

1.  Add the following line to your _clamp.json_:
 ```
 {
   "apache": {...
     "loadmodule": {...
       "unixd_module": "/usr/libexec/apache2/mod_unixd.so"
       ...
     }
   }
 }
 ```

2. Add the following line to <CLAMP_DIRECTORY>/includes/Clamp/ApacheCommand.php:
 ```
 public function executeStart(array $args = array(), array $options = array())
   {
     if (!$this->isRunning($this->getPath($options['pidfile']))) {
       $this->preparePaths($options);
       unset($options['lockfile']);  // THIS LINE NEEDS TO BE ADDED
       ...
 ```

**Comment by jide** [comment]
Thanks @rqelibari,

Feel free to submit a PR !

**Comment by rqelibari** [comment]
For everyone stumbling upon this issue and running el capitan, see this thread for more information:
#19
